<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsAotExcluded>true</IsAotExcluded>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Weave.Silo.Tests" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Weave.ServiceDefaults\Weave.ServiceDefaults.csproj" />
    <ProjectReference Include="..\..\Workspaces\Weave.Workspaces\Weave.Workspaces.csproj" />
    <ProjectReference Include="..\..\Assistants\Weave.Agents\Weave.Agents.csproj" />
    <ProjectReference Include="..\..\Security\Weave.Security\Weave.Security.csproj" />
    <ProjectReference Include="..\..\Security\Weave.Security.Sqlite\Weave.Security.Sqlite.csproj" />
    <ProjectReference Include="..\..\Security\Weave.Security.Postgres\Weave.Security.Postgres.csproj" />
    <ProjectReference Include="..\..\Tools\Weave.Tools\Weave.Tools.csproj" />
    <ProjectReference Include="..\Weave.Silo.Clustering.Redis\Weave.Silo.Clustering.Redis.csproj" />
    <ProjectReference Include="..\Weave.Silo.Clustering.Sqlite\Weave.Silo.Clustering.Sqlite.csproj" />
    <ProjectReference Include="..\Weave.Silo.Clustering.SqlServer\Weave.Silo.Clustering.SqlServer.csproj" />
    <ProjectReference Include="..\Weave.Silo.Clustering.Postgres\Weave.Silo.Clustering.Postgres.csproj" />
    <ProjectReference Include="..\..\Foundation\Weave.SourceGen\Weave.SourceGen.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.Orleans.Server" />
    <PackageReference Include="Microsoft.Orleans.Serialization.SystemTextJson" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

</Project>
