using System.Globalization;
using System.Text;
using Weave.Workspaces.Models;

namespace Weave.Deploy.Translators;

public sealed class GitHubActionsPublisher : IPublisher
{
    public string TargetName => "github-actions";

    public async Task<PublishResult> PublishAsync(WorkspaceManifest manifest, PublishOptions options, CancellationToken ct = default)
    {
        var target = manifest.Targets?.GetValueOrDefault("ci");
        var trigger = target?.Trigger ?? "pull_request";

        var sb = new StringBuilder();
        sb.AppendLine("# Generated by Weave");
        sb.AppendLine(CultureInfo.InvariantCulture, $"name: Weave - {manifest.Name}");
        sb.AppendLine();
        sb.AppendLine("on:");
        sb.AppendLine(CultureInfo.InvariantCulture, $"  {trigger}:");
        sb.AppendLine();
        sb.AppendLine("jobs:");
        sb.AppendLine("  weave-agents:");
        sb.AppendLine("    runs-on: ubuntu-latest");
        sb.AppendLine("    services:");
        sb.AppendLine("      redis:");
        sb.AppendLine("        image: redis:7-alpine");
        sb.AppendLine("        ports:");
        sb.AppendLine("          - 6379:6379");
        sb.AppendLine("    steps:");
        sb.AppendLine("      - uses: actions/checkout@v4");
        sb.AppendLine();
        sb.AppendLine("      - name: Setup .NET");
        sb.AppendLine("        uses: actions/setup-dotnet@v4");
        sb.AppendLine("        with:");
        sb.AppendLine("          dotnet-version: '10.0.x'");
        sb.AppendLine();
        sb.AppendLine("      - name: Start Weave workspace");
        sb.AppendLine("        run: |");
        sb.AppendLine(CultureInfo.InvariantCulture, $"          dotnet run --project src/Weave.Silo -- --workspace={manifest.Name}");
        sb.AppendLine("        env:");
        sb.AppendLine("          REDIS_CONNECTION: localhost:6379");

        // Add agent-specific steps
        if (manifest.Agents is { Count: > 0 })
        {
            foreach (var (name, _) in manifest.Agents)
            {
                sb.AppendLine();
                sb.AppendLine(CultureInfo.InvariantCulture, $"      - name: Run agent '{name}'");
                sb.AppendLine(CultureInfo.InvariantCulture, $"        run: weave agent send {name} \"Execute CI tasks\"");
            }
        }

        var outputDir = Path.Combine(options.OutputPath, ".github", "workflows");
        Directory.CreateDirectory(outputDir);
        var filePath = Path.Combine(outputDir, $"weave-{manifest.Name}.yml");
        await File.WriteAllTextAsync(filePath, sb.ToString(), ct);

        return new PublishResult
        {
            Success = true,
            TargetName = TargetName,
            OutputPath = options.OutputPath,
            GeneratedFiles = [filePath]
        };
    }
}
