using System.Globalization;
using System.Text;
using Weave.Workspaces.Models;

namespace Weave.Deploy.Translators;

public sealed class NomadPublisher : IPublisher
{
    public string TargetName => "nomad";

    public async Task<PublishResult> PublishAsync(WorkspaceManifest manifest, PublishOptions options, CancellationToken ct = default)
    {
        var sb = new StringBuilder();
        sb.AppendLine(CultureInfo.InvariantCulture, $"# Generated by Weave — Nomad job for workspace '{manifest.Name}'");
        sb.AppendLine(CultureInfo.InvariantCulture, $"job \"weave-{manifest.Name}\" {{");
        sb.AppendLine("  datacenters = [\"dc1\"]");
        sb.AppendLine("  type = \"service\"");
        sb.AppendLine();
        sb.AppendLine("  group \"silo\" {");
        sb.AppendLine("    count = 1");
        sb.AppendLine();
        sb.AppendLine("    network {");
        sb.AppendLine("      port \"http\" { static = 5000 }");
        sb.AppendLine("      port \"orleans_silo\" { static = 11111 }");
        sb.AppendLine("      port \"orleans_gw\" { static = 30000 }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    task \"silo\" {");
        sb.AppendLine("      driver = \"docker\"");
        sb.AppendLine("      config {");
        sb.AppendLine("        image = \"weave-silo:latest\"");
        sb.AppendLine("        ports = [\"http\", \"orleans_silo\", \"orleans_gw\"]");
        sb.AppendLine("      }");
        sb.AppendLine("      env {");
        sb.AppendLine(CultureInfo.InvariantCulture, $"        WEAVE_WORKSPACE = \"{manifest.Name}\"");
        sb.AppendLine("      }");
        sb.AppendLine("      resources {");
        sb.AppendLine("        cpu    = 500");
        sb.AppendLine("        memory = 512");
        sb.AppendLine("      }");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.AppendLine("    task \"dapr-sidecar\" {");
        sb.AppendLine("      driver = \"docker\"");
        sb.AppendLine("      config {");
        sb.AppendLine("        image = \"daprio/dapr:latest\"");
        sb.AppendLine("        args  = [\"./daprd\", \"--app-id\", \"weave-silo\", \"--app-port\", \"5000\"]");
        sb.AppendLine("      }");
        sb.AppendLine("      lifecycle { hook = \"prestart\" sidecar = true }");
        sb.AppendLine("      resources {");
        sb.AppendLine("        cpu    = 100");
        sb.AppendLine("        memory = 128");
        sb.AppendLine("      }");
        sb.AppendLine("    }");
        sb.AppendLine("  }");
        sb.AppendLine();
        sb.AppendLine("  group \"redis\" {");
        sb.AppendLine("    count = 1");
        sb.AppendLine("    network { port \"redis\" { static = 6379 } }");
        sb.AppendLine("    task \"redis\" {");
        sb.AppendLine("      driver = \"docker\"");
        sb.AppendLine("      config {");
        sb.AppendLine("        image = \"redis:7-alpine\"");
        sb.AppendLine("        ports = [\"redis\"]");
        sb.AppendLine("      }");
        sb.AppendLine("      resources { cpu = 100; memory = 128 }");
        sb.AppendLine("    }");
        sb.AppendLine("  }");
        sb.AppendLine("}");

        var outputDir = options.OutputPath;
        Directory.CreateDirectory(outputDir);
        var filePath = Path.Combine(outputDir, $"weave-{manifest.Name}.nomad.hcl");
        await File.WriteAllTextAsync(filePath, sb.ToString(), ct);

        return new PublishResult
        {
            Success = true,
            TargetName = TargetName,
            OutputPath = outputDir,
            GeneratedFiles = [filePath]
        };
    }
}
