<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsAotExcluded>true</IsAotExcluded>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
    <RootNamespace>Weave.Deploy.Tests</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../extensions/Weave.Deploy/Weave.Deploy.csproj" />
    <ProjectReference Include="../../src/Weave.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="Shouldly" />
    <PackageReference Include="NSubstitute" />
  </ItemGroup>
</Project>
