<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsAotExcluded>true</IsAotExcluded>
    <RootNamespace>Weave.Mailbox.Host</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Weave.csproj" />
    <ProjectReference Include="../../extensions/Weave.Mailboxes.Sqlite/Weave.Mailboxes.Sqlite.csproj" />
  </ItemGroup>
</Project>
