<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Description>SQLite-backed implementations of Weave.Security stores.</Description>
    <RootNamespace>Weave.Security.Sqlite</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../../src/Weave.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Options" />
    <PackageReference Include="Microsoft.Data.Sqlite" />
  </ItemGroup>
</Project>
