using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Weave.SourceGen;

/// <summary>
/// Emits strongly-typed identifier structs for every partial readonly
/// record struct decorated with <c>[BrandedId]</c>. Each ID gets a
/// <c>Value</c> property, factory/parse helpers, string conversions,
/// <see cref="System.ComponentModel.TypeConverter"/>, and a
/// <see cref="System.Text.Json.Serialization.JsonConverter{T}"/>.
///
/// Orleans cross-actor serialization adapters live in a separate
/// assembly (<c>Weave.Shared.Orleans</c>) so this generator — and the
/// <c>Weave.Shared</c> assembly itself — stay Orleans-free.
/// </summary>
[Generator]
public sealed class BrandedIdGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Weave.Shared.Ids.BrandedIdAttribute";

    private const string AttributeSource = """
        // <auto-generated/>
        #nullable enable

        namespace Weave.Shared.Ids;

        /// <summary>
        /// Marks a partial readonly record struct as a branded (strongly-typed) identifier.
        /// The source generator adds a Value property, factory methods, conversions,
        /// a TypeConverter, and a System.Text.Json JsonConverter.
        /// </summary>
        [global::System.AttributeUsage(global::System.AttributeTargets.Struct, Inherited = false, AllowMultiple = false)]
        internal sealed class BrandedIdAttribute : global::System.Attribute { }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("BrandedIdAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        var structs = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is StructDeclarationSyntax or RecordDeclarationSyntax,
                transform: static (ctx, _) => GetTypeInfo(ctx))
            .Where(static x => x is not null)
            .Select(static (x, _) => x!.Value);

        context.RegisterSourceOutput(structs, static (spc, info) => Execute(spc, info));
    }

    private static (string Name, string Namespace)? GetTypeInfo(GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol)
            return null;

        var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? ""
            : typeSymbol.ContainingNamespace.ToDisplayString();

        return (typeSymbol.Name, ns);
    }

    private static void Execute(SourceProductionContext ctx, (string Name, string Namespace) info)
    {
        var (name, ns) = info;
        var sb = new StringBuilder(1536);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(ns))
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }

        // Struct attributes
        sb.Append("[global::System.ComponentModel.TypeConverter(typeof(")
          .Append(name).AppendLine("TypeConverter))]");
        sb.Append("[global::System.Text.Json.Serialization.JsonConverter(typeof(")
          .Append(name).AppendLine("JsonConverter))]");

        // Struct declaration
        sb.Append("public readonly partial record struct ").Append(name)
          .Append(" : global::System.IComparable<").Append(name).AppendLine(">");
        sb.AppendLine("{");
        sb.AppendLine("    public string Value { get; }");
        sb.AppendLine();
        sb.Append("    public ").Append(name)
          .AppendLine("(string value) => Value = value ?? throw new global::System.ArgumentNullException(nameof(value));");
        sb.AppendLine();
        sb.Append("    public static ").Append(name)
          .AppendLine(" New() => new(global::System.Guid.CreateVersion7().ToString(\"N\"));");
        sb.Append("    public static ").Append(name)
          .AppendLine(" From(string value) => new(value);");
        sb.AppendLine();
        sb.Append("    public static ").Append(name)
          .AppendLine(" Parse(string value) => new(value);");
        sb.Append("    public static bool TryParse(string? value, out ").Append(name).AppendLine(" result)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (value is null) { result = default; return false; }");
        sb.Append("        result = new ").Append(name).AppendLine("(value); return true;");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.Append("    public static ").Append(name).AppendLine(" Empty => default;");
        sb.AppendLine("    public bool IsEmpty => string.IsNullOrEmpty(Value);");
        sb.AppendLine();
        sb.Append("    public static implicit operator string(").Append(name)
          .AppendLine(" id) => id.Value ?? string.Empty;");
        sb.Append("    public static explicit operator ").Append(name)
          .AppendLine("(string value) => new(value);");
        sb.AppendLine();
        sb.AppendLine("    public override string ToString() => Value ?? string.Empty;");
        sb.AppendLine();
        sb.Append("    public int CompareTo(").Append(name)
          .AppendLine(" other) => string.Compare(Value, other.Value, global::System.StringComparison.Ordinal);");
        sb.AppendLine();
        sb.Append("    public static bool operator <(").Append(name).Append(" left, ").Append(name)
          .AppendLine(" right) => left.CompareTo(right) < 0;");
        sb.Append("    public static bool operator >(").Append(name).Append(" left, ").Append(name)
          .AppendLine(" right) => left.CompareTo(right) > 0;");
        sb.Append("    public static bool operator <=(").Append(name).Append(" left, ").Append(name)
          .AppendLine(" right) => left.CompareTo(right) <= 0;");
        sb.Append("    public static bool operator >=(").Append(name).Append(" left, ").Append(name)
          .AppendLine(" right) => left.CompareTo(right) >= 0;");
        sb.AppendLine("}");
        sb.AppendLine();

        // TypeConverter (for config binding, routing, etc.)
        sb.Append("internal sealed class ").Append(name)
          .AppendLine("TypeConverter : global::System.ComponentModel.TypeConverter");
        sb.AppendLine("{");
        sb.AppendLine("    public override bool CanConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Type sourceType) =>");
        sb.AppendLine("        sourceType == typeof(string) || base.CanConvertFrom(context, sourceType);");
        sb.AppendLine();
        sb.AppendLine("    public override object? ConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object value) =>");
        sb.Append("        value is string s ? new ").Append(name)
          .AppendLine("(s) : base.ConvertFrom(context, culture, value);");
        sb.AppendLine();
        sb.AppendLine("    public override object? ConvertTo(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object? value, global::System.Type destinationType) =>");
        sb.Append("        destinationType == typeof(string) && value is ").Append(name)
          .AppendLine(" id ? id.Value : base.ConvertTo(context, culture, value, destinationType);");
        sb.AppendLine("}");
        sb.AppendLine();

        // STJ JsonConverter — AOT-safe (direct reader/writer, no reflection).
        sb.Append("internal sealed class ").Append(name)
          .Append("JsonConverter : global::System.Text.Json.Serialization.JsonConverter<").Append(name).AppendLine(">");
        sb.AppendLine("{");
        sb.Append("    public override ").Append(name)
          .AppendLine(" Read(ref global::System.Text.Json.Utf8JsonReader reader, global::System.Type typeToConvert, global::System.Text.Json.JsonSerializerOptions options)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (reader.TokenType == global::System.Text.Json.JsonTokenType.Null) return default;");
        sb.AppendLine("        if (reader.TokenType != global::System.Text.Json.JsonTokenType.String)");
        sb.Append("            throw new global::System.Text.Json.JsonException($\"Expected string for ")
          .Append(name).AppendLine(", got {reader.TokenType}.\");");
        sb.Append("        return new ").Append(name).AppendLine("(reader.GetString() ?? string.Empty);");
        sb.AppendLine("    }");
        sb.AppendLine();
        sb.Append("    public override void Write(global::System.Text.Json.Utf8JsonWriter writer, ").Append(name)
          .AppendLine(" value, global::System.Text.Json.JsonSerializerOptions options)");
        sb.AppendLine("    {");
        sb.AppendLine("        writer.WriteStringValue(value.Value ?? string.Empty);");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        ctx.AddSource($"{name}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
