using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.Text;

namespace Weave.SourceGen;

/// <summary>
/// Scans the compilation and its referenced assemblies for classes implementing
/// ICommandHandler&lt;,&gt; or IQueryHandler&lt;,&gt; and generates an explicit
/// registration method — no runtime reflection needed.
/// </summary>
[Generator]
public sealed class CqrsRegistrationGenerator : IIncrementalGenerator
{
    private const string CommandHandlerName = "Weave.Shared.Cqrs.ICommandHandler`2";
    private const string QueryHandlerName = "Weave.Shared.Cqrs.IQueryHandler`2";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var handlers = context.CompilationProvider
            .Select(static (compilation, ct) => FindAllHandlers(compilation, ct));

        context.RegisterSourceOutput(handlers, static (spc, list) =>
        {
            if (list.IsEmpty)
                return;
            spc.AddSource("GeneratedCqrsRegistration.g.cs", SourceText.From(GenerateSource(list), Encoding.UTF8));
        });
    }

    private static ImmutableArray<HandlerInfo> FindAllHandlers(Compilation compilation, System.Threading.CancellationToken ct)
    {
        var commandHandler = compilation.GetTypeByMetadataName(CommandHandlerName);
        var queryHandler = compilation.GetTypeByMetadataName(QueryHandlerName);

        if (commandHandler is null && queryHandler is null)
            return ImmutableArray<HandlerInfo>.Empty;

        var results = ImmutableArray.CreateBuilder<HandlerInfo>();

        // Scan referenced assemblies
        foreach (var reference in compilation.SourceModule.ReferencedAssemblySymbols)
        {
            ct.ThrowIfCancellationRequested();
            CollectHandlers(reference.GlobalNamespace, commandHandler, queryHandler, results, ct);
        }

        // Scan current compilation
        CollectHandlers(compilation.GlobalNamespace, commandHandler, queryHandler, results, ct);

        return results.ToImmutable();
    }

    private static void CollectHandlers(
        INamespaceSymbol root,
        INamedTypeSymbol? commandHandler,
        INamedTypeSymbol? queryHandler,
        ImmutableArray<HandlerInfo>.Builder results,
        System.Threading.CancellationToken ct)
    {
        foreach (var type in GetAllTypes(root, ct))
        {
            if (type.IsAbstract || type.TypeKind != TypeKind.Class)
                continue;

            foreach (var iface in type.AllInterfaces)
            {
                if (!iface.IsGenericType)
                    continue;
                var original = iface.OriginalDefinition;

                if ((commandHandler is not null && SymbolEqualityComparer.Default.Equals(original, commandHandler))
                    || (queryHandler is not null && SymbolEqualityComparer.Default.Equals(original, queryHandler)))
                {
                    var fqf = SymbolDisplayFormat.FullyQualifiedFormat;
                    results.Add(new HandlerInfo(
                        type.ToDisplayString(fqf),
                        iface.ToDisplayString(fqf)));
                    break;
                }
            }
        }
    }

    private static IEnumerable<INamedTypeSymbol> GetAllTypes(INamespaceSymbol ns, System.Threading.CancellationToken ct)
    {
        ct.ThrowIfCancellationRequested();

        foreach (var type in ns.GetTypeMembers())
        {
            yield return type;
            foreach (var nested in type.GetTypeMembers())
                yield return nested;
        }

        foreach (var child in ns.GetNamespaceMembers())
        {
            foreach (var type in GetAllTypes(child, ct))
                yield return type;
        }
    }

    private static string GenerateSource(ImmutableArray<HandlerInfo> handlers)
    {
        var sb = new StringBuilder(2048);
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("namespace Weave.Shared.Cqrs;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Source-generated CQRS handler registration — no runtime reflection.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("public static class GeneratedCqrsRegistration");
        sb.AppendLine("{");
        sb.AppendLine("    public static global::Microsoft.Extensions.DependencyInjection.IServiceCollection AddGeneratedCqrsHandlers(");
        sb.AppendLine("        this global::Microsoft.Extensions.DependencyInjection.IServiceCollection services)");
        sb.AppendLine("    {");
        sb.AppendLine("        services.AddSingleton<global::Weave.Shared.Cqrs.ICommandDispatcher, global::Weave.Shared.Cqrs.CommandDispatcher>();");
        sb.AppendLine("        services.AddSingleton<global::Weave.Shared.Cqrs.IQueryDispatcher, global::Weave.Shared.Cqrs.QueryDispatcher>();");

        foreach (var h in handlers)
        {
            sb.Append("        global::Microsoft.Extensions.DependencyInjection.ServiceCollectionServiceExtensions.AddScoped<")
              .Append(h.InterfaceType)
              .Append(", ")
              .Append(h.ImplementationType)
              .AppendLine(">(services);");
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private readonly struct HandlerInfo
    {
        public readonly string ImplementationType;
        public readonly string InterfaceType;

        public HandlerInfo(string implementationType, string interfaceType)
        {
            ImplementationType = implementationType;
            InterfaceType = interfaceType;
        }
    }
}
