using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Weave.SourceGen;

[Generator]
public sealed class BrandedIdGenerator : IIncrementalGenerator
{
    private const string AttributeFullName = "Weave.Shared.Ids.BrandedIdAttribute";

    private const string AttributeSource = """
        // <auto-generated/>
        #nullable enable

        namespace Weave.Shared.Ids;

        /// <summary>
        /// Marks a partial readonly record struct as a branded (strongly-typed) identifier.
        /// The source generator will add a string Value property, factory methods,
        /// conversions, and Orleans serialization attributes.
        /// </summary>
        [global::System.AttributeUsage(global::System.AttributeTargets.Struct, Inherited = false, AllowMultiple = false)]
        internal sealed class BrandedIdAttribute : global::System.Attribute { }
        """;

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        context.RegisterPostInitializationOutput(ctx =>
            ctx.AddSource("BrandedIdAttribute.g.cs", SourceText.From(AttributeSource, Encoding.UTF8)));

        var structs = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                AttributeFullName,
                predicate: static (node, _) => node is StructDeclarationSyntax or RecordDeclarationSyntax,
                transform: static (ctx, _) => GetTypeInfo(ctx))
            .Where(static x => x is not null)
            .Select(static (x, _) => x!.Value);

        context.RegisterSourceOutput(structs, static (spc, info) => Execute(spc, info));
    }

    private static (string Name, string Namespace, bool HasOrleans)? GetTypeInfo(
        GeneratorAttributeSyntaxContext ctx)
    {
        if (ctx.TargetSymbol is not INamedTypeSymbol typeSymbol)
            return null;

        var ns = typeSymbol.ContainingNamespace.IsGlobalNamespace
            ? ""
            : typeSymbol.ContainingNamespace.ToDisplayString();

        var hasOrleans = ctx.SemanticModel.Compilation
            .GetTypeByMetadataName("Orleans.GenerateSerializerAttribute") is not null;

        return (typeSymbol.Name, ns, hasOrleans);
    }

    private static void Execute(
        SourceProductionContext ctx,
        (string Name, string Namespace, bool HasOrleans) info)
    {
        var (name, ns, hasOrleans) = info;
        var sb = new StringBuilder(1024);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (!string.IsNullOrEmpty(ns))
        {
            sb.Append("namespace ").Append(ns).AppendLine(";");
            sb.AppendLine();
        }

        // Attributes
        if (hasOrleans)
            sb.AppendLine("[global::Orleans.Immutable]");

        sb.Append("[global::System.ComponentModel.TypeConverter(typeof(")
          .Append(name).AppendLine("TypeConverter))]");

        // Struct declaration
        sb.Append("public readonly partial record struct ").Append(name)
          .Append(" : global::System.IComparable<").Append(name).AppendLine(">");
        sb.AppendLine("{");

        // Value property
        sb.AppendLine("    public string Value { get; }");
        sb.AppendLine();

        // Constructor
        sb.Append("    public ").Append(name)
          .AppendLine("(string value) => Value = value ?? throw new global::System.ArgumentNullException(nameof(value));");
        sb.AppendLine();

        // Factory methods
        sb.Append("    public static ").Append(name)
          .AppendLine(" New() => new(global::System.Guid.CreateVersion7().ToString(\"N\"));");
        sb.Append("    public static ").Append(name)
          .AppendLine(" From(string value) => new(value);");
        sb.AppendLine();

        // Parse
        sb.Append("    public static ").Append(name)
          .AppendLine(" Parse(string value) => new(value);");
        sb.Append("    public static bool TryParse(string? value, out ").Append(name).AppendLine(" result)");
        sb.AppendLine("    {");
        sb.AppendLine("        if (value is null) { result = default; return false; }");
        sb.Append("        result = new ").Append(name).AppendLine("(value); return true;");
        sb.AppendLine("    }");
        sb.AppendLine();

        // Empty sentinel
        sb.Append("    public static ").Append(name).AppendLine(" Empty => default;");
        sb.AppendLine("    public bool IsEmpty => string.IsNullOrEmpty(Value);");
        sb.AppendLine();

        // Conversions
        sb.Append("    public static implicit operator string(").Append(name)
          .AppendLine(" id) => id.Value ?? string.Empty;");
        sb.Append("    public static explicit operator ").Append(name)
          .AppendLine("(string value) => new(value);");
        sb.AppendLine();

        // ToString
        sb.AppendLine("    public override string ToString() => Value ?? string.Empty;");
        sb.AppendLine();

        // IComparable
        sb.Append("    public int CompareTo(").Append(name)
          .AppendLine(" other) => string.Compare(Value, other.Value, global::System.StringComparison.Ordinal);");
        sb.AppendLine();

        // Comparison operators (CA1036)
        sb.Append("    public static bool operator <(").Append(name).Append(" left, ").Append(name)
          .AppendLine(" right) => left.CompareTo(right) < 0;");
        sb.Append("    public static bool operator >(").Append(name).Append(" left, ").Append(name)
          .AppendLine(" right) => left.CompareTo(right) > 0;");
        sb.Append("    public static bool operator <=(").Append(name).Append(" left, ").Append(name)
          .AppendLine(" right) => left.CompareTo(right) <= 0;");
        sb.Append("    public static bool operator >=(").Append(name).Append(" left, ").Append(name)
          .AppendLine(" right) => left.CompareTo(right) >= 0;");

        sb.AppendLine("}");
        sb.AppendLine();

        // TypeConverter
        sb.Append("internal sealed class ").Append(name)
          .AppendLine("TypeConverter : global::System.ComponentModel.TypeConverter");
        sb.AppendLine("{");
        sb.AppendLine("    public override bool CanConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Type sourceType) =>");
        sb.AppendLine("        sourceType == typeof(string) || base.CanConvertFrom(context, sourceType);");
        sb.AppendLine();
        sb.AppendLine("    public override object? ConvertFrom(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object value) =>");
        sb.Append("        value is string s ? new ").Append(name)
          .AppendLine("(s) : base.ConvertFrom(context, culture, value);");
        sb.AppendLine();
        sb.AppendLine("    public override object? ConvertTo(global::System.ComponentModel.ITypeDescriptorContext? context, global::System.Globalization.CultureInfo? culture, object? value, global::System.Type destinationType) =>");
        sb.Append("        destinationType == typeof(string) && value is ").Append(name)
          .AppendLine(" id ? id.Value : base.ConvertTo(context, culture, value, destinationType);");
        sb.AppendLine("}");

        // Orleans surrogate + converter (cross-assembly serialization)
        if (hasOrleans)
        {
            sb.AppendLine();
            sb.AppendLine("[global::Orleans.GenerateSerializer]");
            sb.Append("internal struct ").Append(name).AppendLine("Surrogate");
            sb.AppendLine("{");
            sb.AppendLine("    [global::Orleans.Id(0)]");
            sb.AppendLine("    public string Value { get; set; }");
            sb.AppendLine("}");
            sb.AppendLine();

            sb.AppendLine("[global::Orleans.RegisterConverter]");
            sb.Append("internal sealed class ").Append(name).Append("SurrogateConverter : global::Orleans.IConverter<")
              .Append(name).Append(", ").Append(name).AppendLine("Surrogate>");
            sb.AppendLine("{");
            sb.Append("    public ").Append(name).Append(" ConvertFromSurrogate(in ").Append(name)
              .Append("Surrogate surrogate) => ").Append(name).AppendLine(".From(surrogate.Value ?? string.Empty);");
            sb.Append("    public ").Append(name).Append("Surrogate ConvertToSurrogate(in ").Append(name)
              .AppendLine(" value) => new() { Value = value.Value ?? string.Empty };");
            sb.AppendLine("}");
        }

        ctx.AddSource($"{name}.g.cs", SourceText.From(sb.ToString(), Encoding.UTF8));
    }
}
