using System.Globalization;
using System.Text;
using Weave.Workspaces.Models;

namespace Weave.Deploy.Translators;

public sealed class DockerComposePublisher : IPublisher
{
    public string TargetName => "docker-compose";

    public async Task<PublishResult> PublishAsync(WorkspaceManifest manifest, PublishOptions options, CancellationToken ct = default)
    {
        var sb = new StringBuilder();
        sb.AppendLine("# Generated by Weave");
        var networkName = manifest.Workspace?.Network?.Name ?? "weave-network";
        sb.AppendLine(CultureInfo.InvariantCulture, $"# Workspace: {manifest.Name}");
        sb.AppendLine();
        sb.AppendLine("services:");

        // Silo service
        sb.AppendLine("  weave-silo:");
        sb.AppendLine("    image: weave-silo:latest");
        sb.AppendLine("    ports:");
        sb.AppendLine("      - \"5000:5000\"");
        sb.AppendLine("      - \"11111:11111\"");
        sb.AppendLine("      - \"30000:30000\"");
        sb.AppendLine("    environment:");
        sb.AppendLine(CultureInfo.InvariantCulture, $"      - WEAVE_WORKSPACE={manifest.Name}");
        sb.AppendLine("    depends_on:");
        sb.AppendLine("      - redis");
        sb.AppendLine("    networks:");
        sb.AppendLine(CultureInfo.InvariantCulture, $"      - {networkName}");
        sb.AppendLine();

        // Redis
        sb.AppendLine("  redis:");
        sb.AppendLine("    image: redis:7-alpine");
        sb.AppendLine("    ports:");
        sb.AppendLine("      - \"6379:6379\"");
        sb.AppendLine("    networks:");
        sb.AppendLine(CultureInfo.InvariantCulture, $"      - {networkName}");
        sb.AppendLine();

        // Tool containers
        if (manifest.Tools is { Count: > 0 })
        {
            foreach (var (name, _) in manifest.Tools)
            {
                ct.ThrowIfCancellationRequested();
                sb.AppendLine(CultureInfo.InvariantCulture, $"  tool-{name}:");
                sb.AppendLine(CultureInfo.InvariantCulture, $"    image: weave-tool-{name}:latest");
                sb.AppendLine("    read_only: true");
                sb.AppendLine("    cap_drop:");
                sb.AppendLine("      - ALL");
                sb.AppendLine("    networks:");
                sb.AppendLine(CultureInfo.InvariantCulture, $"      - {networkName}");
                sb.AppendLine();
            }
        }

        // Network
        sb.AppendLine("networks:");
        sb.AppendLine(CultureInfo.InvariantCulture, $"  {networkName}:");
        sb.AppendLine("    driver: bridge");

        var outputDir = options.OutputPath;
        Directory.CreateDirectory(outputDir);
        var filePath = Path.Combine(outputDir, "docker-compose.yml");
        await File.WriteAllTextAsync(filePath, sb.ToString(), ct);

        return new PublishResult
        {
            Success = true,
            TargetName = TargetName,
            OutputPath = outputDir,
            GeneratedFiles = [filePath]
        };
    }
}
