using System.Globalization;
using System.Text;
using Weave.Shared;
using Weave.Workspaces.Models;

namespace Weave.Deploy.Translators;

public sealed class FlyIoPublisher : IPublisher
{
    public string TargetName => "fly-io";

    public async Task<PublishResult> PublishAsync(WorkspaceManifest manifest, PublishOptions options, CancellationToken ct = default)
    {
        var target = manifest.Targets?.GetValueOrDefault("production");
        var region = target?.Region ?? "iad";
        var minScale = target?.Scaling?.Min ?? 1;
        var maxScale = target?.Scaling?.Max ?? 10;

        var sb = new StringBuilder();
        sb.AppendLine(CultureInfo.InvariantCulture, $"# Generated by Weave — Fly.io config for workspace '{manifest.Name}'");
        sb.AppendLine(CultureInfo.InvariantCulture, $"app = \"weave-{manifest.Name}\"");
        sb.AppendLine(CultureInfo.InvariantCulture, $"primary_region = \"{region}\"");
        sb.AppendLine();
        sb.AppendLine("[build]");
        sb.AppendLine("  dockerfile = \"Dockerfile\"");
        sb.AppendLine();
        sb.AppendLine("[env]");
        sb.AppendLine(CultureInfo.InvariantCulture, $"  WEAVE_WORKSPACE = \"{manifest.Name}\"");
        sb.AppendLine();
        sb.AppendLine("[http_service]");
        sb.AppendLine(CultureInfo.InvariantCulture, $"  internal_port = {WeavePorts.SiloHttp}");
        sb.AppendLine("  force_https = true");
        sb.AppendLine(CultureInfo.InvariantCulture, $"  min_machines_running = {minScale}");
        sb.AppendLine();
        sb.AppendLine("  [[http_service.checks]]");
        sb.AppendLine("    interval = \"10s\"");
        sb.AppendLine("    timeout = \"2s\"");
        sb.AppendLine("    grace_period = \"30s\"");
        sb.AppendLine("    method = \"GET\"");
        sb.AppendLine("    path = \"/health\"");
        sb.AppendLine();
        sb.AppendLine("[[vm]]");
        sb.AppendLine("  size = \"shared-cpu-2x\"");
        sb.AppendLine(CultureInfo.InvariantCulture, $"  min_count = {minScale}");
        sb.AppendLine(CultureInfo.InvariantCulture, $"  max_count = {maxScale}");

        var outputDir = options.OutputPath;
        Directory.CreateDirectory(outputDir);
        var filePath = Path.Combine(outputDir, "fly.toml");
        await File.WriteAllTextAsync(filePath, sb.ToString(), ct);

        return new PublishResult
        {
            Success = true,
            TargetName = TargetName,
            OutputPath = outputDir,
            GeneratedFiles = [filePath]
        };
    }
}
