using System.Globalization;
using Weave.Workspaces.Models;

namespace Weave.Deploy.Translators;

public sealed class KubernetesPublisher : IPublisher
{
    public string TargetName => "kubernetes";

    public async Task<PublishResult> PublishAsync(WorkspaceManifest manifest, PublishOptions options, CancellationToken ct = default)
    {
        var files = new List<string>();
        var outputDir = options.OutputPath;
        Directory.CreateDirectory(outputDir);
        var registry = options.Registry ?? "ghcr.io/weave";
        var target = manifest.Targets?.GetValueOrDefault("staging");
        var replicas = target?.Replicas ?? 1;

        var nsFile = Path.Combine(outputDir, "namespace.yml");
        await File.WriteAllTextAsync(nsFile, string.Create(CultureInfo.InvariantCulture, $"""
            # Generated by Weave
            apiVersion: v1
            kind: Namespace
            metadata:
              name: weave-{manifest.Name}
            """), ct);
        files.Add(nsFile);

        var siloFile = Path.Combine(outputDir, "silo-deployment.yml");
        await File.WriteAllTextAsync(siloFile, string.Create(CultureInfo.InvariantCulture, $"""
            # Generated by Weave
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: weave-silo
              namespace: weave-{manifest.Name}
            spec:
              replicas: {replicas}
              selector:
                matchLabels:
                  app: weave-silo
              template:
                metadata:
                  labels:
                    app: weave-silo
                spec:
                  containers:
                    - name: silo
                      image: {registry}/weave-silo:latest
                      ports:
                        - containerPort: 5000
                        - containerPort: 11111
                        - containerPort: 30000
                      env:
                        - name: WEAVE_WORKSPACE
                          value: "{manifest.Name}"
                        - name: REDIS_CONNECTION
                          value: "redis.weave-{manifest.Name}.svc.cluster.local:6379"
            """), ct);
        files.Add(siloFile);

        var redisFile = Path.Combine(outputDir, "redis.yml");
        await File.WriteAllTextAsync(redisFile, string.Create(CultureInfo.InvariantCulture, $"""
            # Generated by Weave
            apiVersion: apps/v1
            kind: StatefulSet
            metadata:
              name: redis
              namespace: weave-{manifest.Name}
            spec:
              serviceName: redis
              replicas: 1
              selector:
                matchLabels:
                  app: redis
              template:
                metadata:
                  labels:
                    app: redis
                spec:
                  containers:
                    - name: redis
                      image: redis:7-alpine
                      ports:
                        - containerPort: 6379
            ---
            apiVersion: v1
            kind: Service
            metadata:
              name: redis
              namespace: weave-{manifest.Name}
            spec:
              selector:
                app: redis
              ports:
                - port: 6379
            """), ct);
        files.Add(redisFile);

        var svcFile = Path.Combine(outputDir, "silo-service.yml");
        await File.WriteAllTextAsync(svcFile, string.Create(CultureInfo.InvariantCulture, $"""
            # Generated by Weave
            apiVersion: v1
            kind: Service
            metadata:
              name: weave-silo
              namespace: weave-{manifest.Name}
            spec:
              selector:
                app: weave-silo
              ports:
                - name: http
                  port: 5000
                - name: orleans-silo
                  port: 11111
                - name: orleans-gateway
                  port: 30000
            """), ct);
        files.Add(svcFile);

        return new PublishResult
        {
            Success = true,
            TargetName = TargetName,
            OutputPath = outputDir,
            GeneratedFiles = files
        };
    }
}
